import Head from 'next/head'
import Image from 'next/image'
import app from '../dev.png'
import screen from '../screen.png'
import { HiDesktopComputer, HiOutlineDeviceMobile } from 'react-icons/hi';
import { AiOutlineMenu } from 'react-icons/ai';
import { MdOutlineDesignServices } from 'react-icons/md';
import { RiGuideFill } from 'react-icons/ri';


export default function Home() {
  return (
    <>
      <Head>
        <title>DEV SOM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* header */}
      <div className='bg-[#007DFE] flex justify-between px-10 py-2'>
        {/* left */}
        <div className='flex items-center gap-24'>
          <h1 className='text-[23px] font-bold uppercase text-white'>dev<span className='text-[#252B43]'> som</span></h1>

          <div className='justify-center items-center gap-x-3 text-white hidden md:flex'>
            <p className='hover:bg-[#252B43] cursor-pointer py-4 px-6 rounded-sm'>Home</p>
            <p className='hover:bg-[#252B43] cursor-pointer py-4 px-6 rounded-sm'>About</p>
            <p className='hover:bg-[#252B43] cursor-pointer py-4 px-6 rounded-sm'>Contact</p>
           </div>
        </div>

        {/* right */}
        <div className='flex gap-x-4'>
          <div className='gap-x-4 hidden md:flex'>
            <button className='text-white border-2 border-white hover:border-0 hover:bg-white hover:text-[#252B43] px-6 rounded-sm py-3'>Register</button>
          <button className='bg-[#252B43] text-white px-6 rounded-sm py-2'>Login</button>
          </div>

          <div className='block md:hidden'>
            <AiOutlineMenu className='text-white h-6 w-6'/>
          </div>
          
        </div>
      </div>

      {/* showcase */}
      <div className='grid md:grid-cols-2 px-10 bg-white justify-center pt-32'>

        <div className='flex flex-col justify-center mx-10'>
          <p className='text-[#007DFE] text-[35px] md:text-[4rem] capitalize font-bold'>Getting your life together</p>
          <p className='text-black'>We recommend creating a new Next.js app using create-next-app, which sets up everything automatically for you.You don't need to create an empty directory.</p>
          <div className='mt-3'>
          <button className='bg-[#252B43] text-white px-6 uppercase rounded-sm py-3 inline'>Get start</button>
          </div>
        </div>
        <div className='flex justify-center'>
          <Image src={app} className='h-full w-[50%]' alt='app'/>
        </div>

      </div>

      {/* services */}
      <div className='mt-10'>
        <p className='text-[23px] font-bold uppercase text-[#007DFE] text-center'>Our srvices</p>
        <div className='grid grid-cols-1  md:grid-cols-4 justify-center items-center m-6 md:m-10 md:gap-6 gap-2'>

        <div className='drop-shadow-lg bg-white rounded-md flex flex-col justify-center items-center p-10 hover:border-[#007DFE] hover:border-2'>
        <HiDesktopComputer className='h-10 w-10 text-[#007DFE]'/>
          <p className='text-[#252B43] text-[23px] font-medium'>Web Design</p>
        </div>

        <div className='drop-shadow-lg bg-white rounded-md flex flex-col justify-center items-center p-10 hover:border-[#007DFE] hover:border-2'>
        <MdOutlineDesignServices className='h-10 w-10 text-[#007DFE]'/>
          <p className='text-[#252B43] text-[23px] font-medium'>UI & UX Design</p>
        </div>

        <div className='drop-shadow-lg bg-white rounded-md flex flex-col justify-center items-center p-10 hover:border-[#007DFE] hover:border-2'>
        <RiGuideFill className='h-10 w-10 text-[#007DFE]'/>
          <p className='text-[#252B43] text-[23px] font-medium'>Consaltant</p>
        </div>

        <div className='drop-shadow-lg bg-white rounded-md flex flex-col justify-center items-center p-10 hover:border-[#007DFE] hover:border-2'>
        <HiOutlineDeviceMobile className='h-10 w-10 text-[#007DFE]'/>
          <p className='text-[#252B43] text-[23px] font-medium'>App Development</p>
        </div>

       
      </div>
      </div>
      </main>
    </>
  )
}
